version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8000}
    environment:
      - NODE_ENV=production
      # Public URL used by the browser to reach the backend (host port mapping)
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8000}
      # Internal URL used by server-side code inside the frontend container
      - INTERNAL_BACKEND_URL=${INTERNAL_BACKEND_URL:-http://backend:8000}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge
